name = input("Įveskite savo vardą")
print(" vardas: " + str(name))
age = input ("Įveskite savo amžių:")
print(" vardas: " + str(age))
print(" Sveiki " + str(name) + ",jums yra " + str(age) + " metų")
